name: Deploy to Hostinger VPS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add Known Hosts
      run: ssh-keyscan -H ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Server-Side Deploy & Build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo "Starting Server-Side Deployment..."
          cd /var/www/tfcc
          
          echo "Pulling Latest Source..."
          git reset --hard HEAD
          git pull origin main
          
          echo "Building Server Environment..."
          cd /var/www/tfcc/server
          npm install --production --no-audit --no-fund
          
          echo "Building Client Environment..."
          cd /var/www/tfcc/client
          npm install --no-audit --no-fund
          npm run build --emptyOutDir
          
          echo "Cycling Process Manager..."
          pm2 delete tfcc-backend || true
          cd /var/www/tfcc/server
          pm2 start index.js --name tfcc-backend --time
          
          echo "Deployment Protocol Complete."
